### ISSUE TITLE
키보드 이외의 다른 변화에도 반응합니다.

### ISSUE THREAD

**Issue by iz000** [ParkSangGwon/TedKeyboardObserver#3]
![mobizen_20190228_172741 mp4](https://user-images.githubusercontent.com/14345431/53552357-7f597d00-3b7e-11e9-95f0-c385471b6a7b.gif)

소프트 홈버튼이 있는 경우 홈버튼의 설정 변경에 따라서도 옵저버가 반응합니다.

**Comment by ted-prnd** [comment]
@iz000 
`1.0.0-alpha4`에서 해결되었습니다.
